database:
    url: mysql://root:03545328@127.0.0.1:3306/lakyblog

logging:
    version: 1
    formatters:
        simple:
            format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
    handlers:
        file:
            class: logging.handlers.TimedRotatingFileHandler
            level: DEBUG
            formatter: simple
            filename: /tmp/log/lakyblog.log
            when: 'D'
            backupCount: 30
    loggers:
        lakyblog:
            level: DEBUG
            handlers: [file]
            propagate: no
